export default {
  IS_LOGGED: "IS_LOGGED",
  IS_LOADING: "IS_LOADING",
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_FOLLOWERS: "SET_FOLLOWERS",
  SET_FOLLOWINGS: "SET_FOLLOWINGS",
  SET_ORDERS: "SET_ORDERS",
  SET_FEED: "SET_FEED",
  SET_INFLUENCERS: "SET_INFLUENCERS",
  SET_MYFAVORITES: "SET_MYFAVORITES",
};
